udistrital/planeacion_mid

.gitignore
conf/app.conf
controllers/arbol.go
helpers/arbolHelper/arbol.helper.go
main.go
models/arbol.go
models/respuesta.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml
tests/default_test.go

hotfix: Ajustes de status ok 

---

README.md
routers/router.go

hotfix:ajuste de ruta

---

.gitignore
controllers/arbol.go
helpers/arbolHelper/arbol.helper.go
main.go
routers/commentsRouter_controllers.go
routers/router.go
tests/default_test.go

hotfix: Ajuste para despliegue

hotfix: Ajuste para despliegue 

---

.drone.yml
conf/app.conf
controllers/formato.go
helpers/arbolHelper/arbol.helper.go
helpers/formatoHelper/formato.helper.go
models/formato.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

management: construcción de JSON con parametrización para retorno al cliente

management: construcción de JSON con parametrización para retorno al cliente

---

controllers/formulacion.go
helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go
models/formato.go
routers/commentsRouter_controllers.go
routers/router.go

feat:Funcion para el clonado de planes

feat:Funcion para el clonado de planes

---

controllers/formato.go
helpers/formatoHelper/formato.helper.go
swagger/swagger.json
swagger/swagger.yml

feat: ajuste método para campo observación. Característica #18

feat: ajuste método para campo observación. Característica #18

---

helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste en mensajes mostrados por consola

fix: Ajuste en mensajes mostrados por consola

---

.drone.yml

hotfix: se comenta step go_run_test temporalmente mientra se encuentra el motivo de su falla

hotfix: se comenta step go_run_test temporalmente mientra se encuentra el motivo de su falla

---

helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go

feat: ajustes de métodos para select dinámico. Característica #73

feat: ajustes de métodos para select dinámico. Característica #73

---

controllers/formulacion.go
helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go

management: ajustes de métodos para select dinámico

management: ajustes de métodos para select dinámico

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat:Funciones para versionamiento de planes

feat:Funciones para versionamiento de planes

---

controllers/formulacion.go
routers/commentsRouter_controllers.go

feat: funcionalidad para desactivar identificación. Característica #113

feat: funcionalidad para desactivar identificación. Característica #113

---

controllers/formulacion.go
swagger/swagger.json
swagger/swagger.yml

fix: swagger doc & fix code

---

controllers/formulacion.go
helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

hotfix: ajuste de swagger y error de merge

hotfix: ajuste de swagger y error de merge

---

helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go

fix: observaciones

---

conf/app.conf
controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: funciones para obtener ponderaciones de actividades

feat: funciones para obtener ponderaciones de actividades y rubros 

---

conf/app.conf
controllers/formulacion.go
helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: funciones para obtener ponderaciones de actividades y rubros

management: funciones para obtener ponderaciones de actividades y rubros

---

conf/app.conf
controllers/formulacion.go
swagger/swagger.json
swagger/swagger.yml

fix: Ajuste función get_rubros

fix: Ajuste función get_rubros

---

helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste Petición get_rubros

fix: Ajuste Peticion Get Rubros

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste para versionamiento de indentificaciones

fix: Ajuste para versionamiento de indentificaciones

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: Ajuste para versionamiento de identificaciones

hotfix: Ajuste para versionamiento de indentificaciones

---

controllers/formulacion.go

fix:Ajustes función versionar_plan

fix:Ajustes función versionar_plan

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: Ajuste función versionar_plan

hotfix: Ajuste funcion versionar_plan

---

conf/app.conf
controllers/formulacion.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Funcion get_unidades

---

conf/app.conf
controllers/formulacion.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Función get_unidades para formulación

feat: Función get_unidades para formulación

---

controllers/formulacion.go

fix: Ajuste para la carga de identificaciones

fix: Ajuste para la carga de identificaciones

---

controllers/formulacion.go

fix: Ajuste funcion get_all_identificaciones

fix: Ajuste funcion get_all_identificaciones

---

conf/app.conf
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

feat: Controlador para las funciones de seguimiento con documentación actualizada

feat: Controlador para las funciones de seguimiento con documentacion actualizada

---

conf/app.conf
controllers/formulacion.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

mangament: Controlador para las funciones de seguimiento con documentacion actualizada #68

mangament: Controlador para las funciones de seguimiento con documentacion actualizada #68

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: Ajuste de peticion para manejo correcto de la variable de entorno

fix: Ajuste de peticion para manejo correcto de la variable de entorno

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Funciones para gestión de seguimiento

feat: Funciones para gestion de seguimiento

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: Funciones para gestion de seguimiento

management: Funciones para gestion de seguimiento

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Funciones para carga de informacion de actividades

feat: Funciones para carga de informacion de actividades

---

controllers/formulacion.go
controllers/seguimiento.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Funciones para guardado y carga de seguimiento

feat: Funciones para guardado y carga de seguimiento

---

controllers/arbol.go
controllers/formato.go
controllers/formulacion.go
controllers/seguimiento.go
helpers/arbolHelper/arbol.helper.go
helpers/formulacionHelper/formulacion.helper.go
helpers/seguimientoHelper/seguimiento.helper.go

fix: Ajustes variables de entorno y funciones para formulacion

fix: Ajustes variables de entorno y funciones para formulacion

---

helpers/formatoHelper/formato.helper.go

fix: Ajustes peticiones para planes_service

fix: Ajustes peticiones para planes_service

---

controllers/seguimiento.go

fix: ajuste petición

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: Ajuste funcion para cargar informacion de actividad

fix: Ajuste funcion para cargar informacion de actividad

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: ajuste de función de seguimiento

hotfix: ajuste de función de seguimiento 

---

controllers/reportes.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

management: desarrollo de la función de desagregado de los planes de acción

management: desarrollo de la función de desagregado de los planes de acción 

---

.drone.yml

mangement: Ajustes servicio de reportes plan de acción de funcionamiento

mangement: Ajustes servicio de reportes plan de acción de funcionamiento 

---

helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste funcion get all actividades para formulacion

fix: Ajuste funcion get all actividades para formulacion

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

fix: Ajustes para nueva armonizacion

fix: Ajustes para nueva armonizacion

---

README.md
static/Documento.txt

hotfix: Creación carpeta static para reportes

hotfix: Creación carpeta static para reportes

---

controllers/reportes.go

fix ajuste creacion del excel

---

static/Documento.txt

hotfix: ajuste de variable para la cración de excel

hotfix: ajuste de variable para la cración de excel 

---

conf/app.conf
controllers/reportes.go
static/Documento.txt

cambio en la forma de envío del excel

fix: cambio en la forma de envío del excel

---

conf/app.conf
controllers/arbol.go
controllers/formulacion.go
helpers/arbolHelper/arbol.helper.go
models/tercero.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Función de vinculación por usuario y funciones para activar o desactivar rama

feat: Funcion de vinculacion por usuario y funciones para arbol

---

controllers/formulacion.go
controllers/seguimiento.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

fix: Ajuste para guardado de fechas para seguimiento

fix: Ajuste para guardado de fechas para seguimiento

---

controllers/formulacion.go

hotfix: Ajuste carga de indentificacion docente #118

hotfix: Ajuste carga de indentificacion docente #118

---

controllers/arbol.go

fix: Ajustes para activar y desactivar planes o nodos

fix: Ajustes para activar y desactivar planes o nodos

---

controllers/arbol.go
controllers/formulacion.go

hotfix: Ajustes para activar y desactivar planes o nodos #120

hotfix: Ajustes para activar y desactivar planes o nodos #120

---

controllers/arbol.go

fix: Ajuste arbol

---

controllers/arbol.go

hotfix: Ajuste arbol

---

controllers/formulacion.go
controllers/reportes.go

fix: Ajuste respuesta de vinculacion de tercero y respuesta de reporte general

fix: Ajuste respuesta de vinculacion de tercero y respuesta de reporte general

---

controllers/formulacion.go

fix: Ajuste peticion de planes

fix: Ajuste peticion de planes

---

controllers/formulacion.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: Ajuste de consulta de trimestres por desincronización de id el api de parametros

hotfix: Ajuste de consulta de trimestres por desincronización de id el api de parametros 

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Reportes de necesidades generales

feat: Reportes de necesidades generales

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: : Reportes de necesidades generales

management: : Reportes de necesidades generales

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Función para verificación de identificaciones

feat: Funcion para verificacion de identificaciones

---

helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste funcion verificacion de identificaciones

fix: Ajuste funcion verificacion de identificaciones

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste para respuesta verificacion identificaciones

fix: Ajuste para respuesta verificacion identificaciones

---

controllers/reportes.go

fix: Ajuste carga indicadores reportes

fix: Ajuste carga indicadores reportes

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: Ajustes para reportes

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: Ajustes para reporte de unidad y formato de moneda

fix: Ajustes para reporte de unidad y formato de moneda

---

controllers/reportes.go

fix: Ajuste para suma de rubros reporte necesidades

fix: Ajuste para suma de rubros reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajuste para suma de rubros reporte necesidades

hotfix: Ajuste para suma de rubros reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: Ajuste para reporte de unidad y valores de reportes

fix: Ajuste para reporte de unidad y valores de reportes

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajuste para reporte de unidad y valores de reportes

hotfix: Ajuste para reporte de unidad y valores de reportes

---

controllers/reportes.go

fix: Ajuste suma rubros reporte necesidades

fix: Ajuste suma rubros reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajuste suma rubros reporte necesidades

hotfix: Ajuste suma rubros reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: Ajuste sumas reporte necesidades

fix: Ajuste sumas reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajuste sumas reporte necesidades

hotfix: Ajuste sumas reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: Ajustes nuevas columnas plan anual por unidad

fix: Ajustes nuevas columnas plan anual por unidad

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajustes nuevas columnas plan anual por unidad

hotfix: Ajustes nuevas columnas plan anual por unidad

---

helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste carga de actividad

fix: Ajuste carga de actividad

---

helpers/formulacionHelper/formulacion.helper.go
helpers/reportesHelper/reportes.helper.go

hotfix: Ajuste carga de actividad

hotfix: Ajuste carga de actividad

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: Ajuste vinculación nuevo cargo

hotfix: Ajuste vinculación nuevo cargo

---

controllers/formulacion.go

fix: Ajuste consulta vinculacion

fix: Ajuste consulta vinculacion

---

controllers/formulacion.go

hotfix: Ajuste consulta vinculacion

hotfix: Ajuste consulta vinculacion

---

controllers/formulacion.go

Se añade consulta a Oikos para incluir Protecto Planestic-ud a la lista de unidades.

fix: Añade consulta a PROYECTO PLANESTIC-UD

---

controllers/formulacion.go

Revert "fix: Añade consulta a PROYECTO PLANESTIC-UD"

Revert "fix: Añade consulta a PROYECTO PLANESTIC-UD"

---

controllers/formulacion.go

hotfix: Añade consulta a PROYECTO PLANESTIC-UD

hotfix: Añade consulta a PROYECTO PLANESTIC-UD

---

controllers/formulacion.go

- Separación de variable auxiliar.

fix: ajuste consulta get_all_identificacion

---

controllers/formulacion.go

hotfix: ajuste consulta get_all_identificacion

hotfix: ajuste consulta get_all_identificacion 

---

controllers/formulacion.go

hot fix: reajuste consulta get_all_identificacion

hot fix: reajuste consulta get_all_identificacion

---

controllers/formulacion.go

hotfix: Add dependencia biblioteca en Formulacion/GetUnidades()

hotfix: Add dependencia biblioteca en Formulacion/GetUnidades()

---

controllers/formulacion.go

hotfix: ajuste de inclusión de oficina subsitema de la seguridad y salud

hotfix: ajuste de inclusión de oficina subsitema de la seguridad y salud

---

controllers/formulacion.go

hotfix: Ajuste para la inclusión de la unidades Unesco,Actas, I3+ y publicaciones

hotfix: Ajuste para la inclusión de la unidades Unesco,Actas, I3+ y publicaciones

---

controllers/formulacion.go

fix: guardado de indicadores opcionales

fix: guardado de indicadores opcionales

---

controllers/formulacion.go

hotfix: guardado de indicadores opcionales

hotfix: guardado de indicadores opcionales

---

controllers/formulacion.go

hotfix:ajuste de reportes por unidad plan de acción de funcionamiento

hotfix:ajuste de reportes por unidad plan de acción de funcionamiento

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Correccion de nombre hoja reportes

hotfix: Correccion de nombre hoja reportes

---

controllers/reportes.go

hotfix: Cambio de vigencia reporte

hotfix: Cambio de vigencia reporte 

---

controllers/reportes.go

management: Se adiciona columna de producto esperado en reportes por unidades

management: Se adiciona columna de producto esperado en reportes por unidades

---

controllers/reportes.go

hotfix: Prueba correccion reporte general

hotfix: Prueba correccion reporte general

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

fix: Ajuste en la creación de actividades

fix: Ajuste en la creación de actividades

---

controllers/formulacion.go
controllers/reportes.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: Ajuste en la creación de actividades

hotfix: Ajuste en la creación de actividades

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: Update de actividades 

---

controllers/formulacion.go

fix: guardado de nueva información en actividad

fix: guardado de nueva información en actividad

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: guardado de nueva información en actividad

hotfix: guardado de nueva información en actividad

---

controllers/formulacion.go
helpers/reportesHelper/reportes.helper.go

hotfix: Correccion en calculo de valores reportes

hotfix: Correccion en calculo de valores reportes

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: : Cambios en reporte de necesidades

hotfix: : Cambios en reporte de necesidades

---

helpers/formulacionHelper/formulacion.helper.go

fix: ajuste de error para primer actividad

fix: ajuste de error para primer actividad

---

controllers/reportes.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: ajuste de actividad cero

hotfix: ajuste de actividad cero

---

controllers/reportes.go
helpers/formulacionHelper/formulacion.helper.go

mangement: reporte necesidades unid totales

mangement: reporte necesidades unid totales 

---

helpers/formulacionHelper/formulacion.helper.go

fix: ajuste en orden de actividades

fix: ajuste en orden de actividades

---

controllers/reportes.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: ajuste en orden de actividades

hotfix: ajuste en orden de actividades

---

controllers/formulacion.go

fix: ajuste en índice

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: ajuste en índice

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

fix: llamado a campos vacíos que rompen consultas

fix: llamado a campos vacíos que rompen consultas

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go

hotfix: llamado a campos vacíos que rompen consultas

hotfix: llamado a campos vacíos que rompen consultas

---

controllers/formulacion.go
controllers/reportes.go
helpers/formulacionHelper/formulacion.helper.go
helpers/reportesHelper/reportes.helper.go

management: Se agregan contratistas al reporte de necesidades

management: Se agregan contratistas al reporte de necesidades

---

controllers/formulacion.go

fix: ajuste de guardado de información opcional en actividades
ordenado de contratistas y recursos

fix: ajuste de guardado de información opcional en actividades

---

controllers/formulacion.go
controllers/reportes.go

hotfix: Se corrige error al mostrar reporte necesidades

hotfix: Se corrige error al mostrar reporte necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: correccion de peticiones para reporte general

hotfix: correccion de peticiones para reporte general

---

helpers/reportesHelper/reportes.helper.go

hotfix: Cambios para reporte general

hotfix: Cambios para reporte general 

---

helpers/reportesHelper/reportes.helper.go

hotfix: Reporte individual sin rubro en contratistas

hotfix: Reporte individual sin rubro en contratistas

---

controllers/formulacion.go

fix: ajuste en calculo de ponderado

fix: ajuste en calculo de ponderado

---

controllers/formulacion.go
helpers/reportesHelper/reportes.helper.go

hotfix: ajuste en calculo de ponderado

hotfix: ajuste en calculo de ponderado

---

controllers/formulacion.go
controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: Optimizacion de tiempo al generar reporte general

hotfix: Optimizacion de tiempo al generar reporte general

---

controllers/reportes.go

hotfix:  Orden por index de actividad en los reportes individual y general

hotfix:  Orden por index de actividad en los reportes individual y general

---

controllers/reportes.go

hotfix: Ajustes en peticiones y unidades totales

hotfix: Ajustes en peticiones y unidades totales

---

controllers/formulacion.go

fix: validación para vicerrectoria academica

fix: validación para vicerrectoria academica

---

controllers/formulacion.go
controllers/reportes.go

hotfix: validación para vicerrectoria academica

hotfix: validación para vicerrectoria academica

---

controllers/seguimiento.go

fix: ajuste en la vigencia del aval de planes

fix: ajuste en la vigencia del aval de planes

---

controllers/reportes.go
controllers/seguimiento.go

feat: integración de periodos-seguimientos y eliminación de página en blanco en reportes. udistrital/planeacion_cliente#574

feat: integración de periodos-seguimientos. udistrital/planeacion_cliente#574

---

controllers/reportes.go
controllers/seguimiento.go

management: integración de periodos-seguimientos. udistrital/planeacion_cliente#574 #293

management: integración de periodos-seguimientos. udistrital/planeacion_cliente#574 #293

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
helpers/utilidades.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: carga de información para actividad especifica. udistrital/planeacion_cliente#575

feat: carga de información para actividad especifica. udistrital/planeacion_cliente#575

---

controllers/reportes.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
helpers/utilidades.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: carga de información para actividad especifica. udistrital/planeacion_cliente#575

management: carga de información para actividad especifica. udistrital/planeacion_cliente#575 

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
helpers/utilidades.go
models/SendJsonHeader.go
models/gestor_documental.go

feat: integración de servicio de gestión documental. udistrital/planeacion_cliente#585

feat: integración de servicio de gestion documental

---

conf/app.conf

fix: ajuste de variable de entorno. udistrital/planeacion_cliente#585

fix: ajuste de variable de entorno. udistrital/planeacion_cliente#585

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

feat: cargue de componente cuantitativo. udistrital/planeacion_cliente#591

feat: cargue decomponete cuantitativo. udistrital/planeacion-cliente#591

---

conf/app.conf
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

management:  cargue decomponete cuantitativo. udistrital/planeacion-cliente#591

management:  cargue decomponete cuantitativo. udistrital/planeacion-cliente#591

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Guardado de componente cualitativo y cuantitativo y reporte de actividades y seguimientos. udistrital/planeacion_cliente#596

feat: Guardado de componente cualitativo y cuantitativo y reporte de actividades y seguimientos. udistrital/planeacion_cliente#596

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: Guardado de componente cualitativo y cuantitativo y reporte de actividades y seguimientos. udistrital/planeacion_cliente#596

management: Guardado de componente cualitativo y cuantitativo y reporte de actividades y seguimientos. udistrital/planeacion_cliente#596 

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Integración de servicios para comentarios de seguimientos. udistrital/planeacion_cliente#612

feat: Integración de servicios para comentarios de seguimientos. udistrital/planeacion_cliente#612

---

controllers/arbol.go
controllers/formato.go
controllers/formulacion.go
controllers/reportes.go
controllers/seguimiento.go
main.go
swagger/swagger.json
swagger/swagger.yml

fix: se ajustan las respuestas para seguir con el estándar udistrital/planeacion_cliente#594

Merge from fix/ajustes_seguridad to develop

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Integración de servios para flujo de estados de seguimientos de plan de acción. udistrital/planeacion_cliente#617

feat: Integración de servios para flujo de estados de seguimientos de plan de acción. udistrital/planeacion_cliente#617

---

controllers/arbol.go
controllers/formato.go
controllers/formulacion.go
controllers/reportes.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
main.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management: Integración de servios para flujo de estados de seguimientos de plan de acción. udistrital/planeacion_cliente#617

management: Integración de servios para flujo de estados de seguimientos de plan de acción. udistrital/planeacion_cliente#617

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

feat: ajustes para modulo de seguimiento de plan de acción. udistrital/planeacion_cliente#624

feat: ajustes para modulo de seguimiento de plan de acción. udistrital/planeacion_cliente#624

---

controllers/seguimiento.go

fix: carga de actividades.  udistrital/planeacion_cliente#638

fix: carga de actividades.  udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

Hotfix: carga de actividades.  udistrital/planeacion_cliente#638

Hotfix: carga de actividades.  udistrital/planeacion_cliente#638

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: ajuste en carga de datos de seguimiento. udistrital/planeacion_cliente#638

fix: ajuste en carga de datos de seguimiento. udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: ajuste en carga de datos de seguimiento. udistrital/planeacion_cliente#638

hotfix: ajuste en carga de datos de seguimiento. udistrital/planeacion_cliente#638

---

models/gestor_documental.go

fix: prueba en documento. udistrital/planeacion_cliente#638

fix: prueba en documento. udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
models/gestor_documental.go

fix: Ajustes en componente de seguimiento. udistrital/planeacion_cliente#638

fix: Ajustes en componente de seguimiento. udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
models/gestor_documental.go

hotfix: Ajustes en componente de seguimiento. udistrital/planeacion_cliente#638

hotfix: Ajustes en componente de seguimiento. udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
helpers/utilidades.go

fix: ajuste en respuesta de evidencias. udistrital/planeacion_cliente#638

fix: ajuste en respuesta de evidencias. udistrital/planeacion_cliente#638

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
helpers/utilidades.go
models/gestor_documental.go

hotfix: ajuste en respuesta de evidencias. udistrital/planeacion_cliente#638

hotfix: ajuste en respuesta de evidencias. udistrital/planeacion_cliente#638

---

controllers/evalucion.go
controllers/seguimiento.go
helpers/evaluacionHelper/evaluacion.helper.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

feat: Evaluación de planes de acción udistrital/planeacion_cliente#646 , udistrital/planeacion_cliente#658 y udistrital/planeacion_cliente#659

feat: Evaluación de planes de acción udistrital/planeacion_cliente#646 , udistrital/planeacion_cliente#658 y udistrital/planeacion_cliente#659

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: ajustes en la carga del componente de seguimiento

fix: ajustes en la carga del componente de seguimiento

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

feat: mejora en tiempos generales. udistrital/planeacion_cliente#665

feat: mejora en tiempos generales. udistrital/planeacion_cliente#665

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

feat: optimización de planes por unidad. udistrital/planeacion_cliente#665

feat: optimización de planes por unidad. udistrital/planeacion_cliente#665

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

management: ajuste de optimización de reporte de unidad para tiempo de respuesta

management: ajuste de optimización de reporte de unidad para tiempo de respuesta 

---

Dockerfile

hotfix: ajuste de dockerfile para el manejo de carpeta static

hotfix: ajuste de dockerfile para el manejo de carpeta static

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go

feat: se implementa consumo del cliente a controlador inversion e issue 666

feat: se implementa consumo del cliente a controlador inversion e issue 666

---

controllers/inversion.go
routers/commentsRouter_controllers.go
swagger/swagger.json

fix: actualizacion documento swagger y corrección escritura rutas controlador inversión

fix: actualizacion documento swagger y correccion escritura rutas controlador inversion

---

controllers/formulacion.go
controllers/inversion.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Cambios en la consulta de rubros planes de acción. udistrital/planeacion_cliente#673

feat: Cambios en la consulta de rubros planes de acción. udistrital/planeacion_cliente#673

---

controllers/inversion.go

fix: correcion en consulta en controlador inversion

fix: correcion en consulta en controlador inversion

---

controllers/formulacion.go
controllers/reportes.go

fix: ajuste en reporte de necesidades. udistrital/planeacion_cliente#669

fix: ajuste en reporte de necesidades. udistrital/planeacion_cliente#669

---

controllers/formulacion.go
controllers/reportes.go
helpers/seguimientoHelper/seguimiento.helper.go

management: ajustes a calculos del modulo de seguimiento

management: ajustes a calculos del modulo de seguimiento 

---

controllers/evalucion.go
controllers/reportes.go
controllers/seguimiento.go
helpers/evaluacionHelper/evaluacion.helper.go
helpers/reportesHelper/reportes.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Integración de reporte de evaluación de planes de acción. udistrital/planeacion_cliente#684

feat: Integración de reporte de evaluación de planes de acción. udistrital/planeacion_cliente#684

---

controllers/evalucion.go
controllers/reportes.go
controllers/seguimiento.go
helpers/evaluacionHelper/evaluacion.helper.go
helpers/reportesHelper/reportes.helper.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

managment:  Integración de reporte de evaluación de planes de acción. udistrital/planeacion_cliente#684

managment:  Integración de reporte de evaluación de planes de acción. udistrital/planeacion_cliente#684

---

controllers/formulacion.go
controllers/inversion.go
controllers/reportes.go
controllers/seguimiento.go

feat: Integración de gráficos a reporte de evaluación plan de acción. udistrital/planeacion_cliente#696

feat: Integración de gráficos a reporte de evaluación plan de acción. udistrital/planeacion_cliente#696

---

controllers/reportes.go
helpers/seguimientoHelper/seguimiento.helper.go

fix: Ajustes en seguimiento y reportes de planes de acción

fix: Ajustes en seguimiento y reportes de planes de acción

---

controllers/inversion.go
helpers/formulacionHelper/formulacion.helper.go
helpers/inversionHelper/inversion.helper.go
helpers/utilidades.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Modulo de proyectos de inversión. udistrital/planeacion_cliente#695

feat: Modulo de proyectos de inversión. udistrital/planeacion_cliente#695

---

controllers/reportes.go
controllers/seguimiento.go

fix: ajuste de guardado información seguimiento planes de acción

fix: ajuste de guardado información seguimiento planes de acción

---

controllers/reportes.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: Integración de verificación de reportes. udistrital/planeacion_cliente#705

feat: Integración de verificación de reportes. udistrital/planeacion_cliente#705

---

controllers/reportes.go
controllers/seguimiento.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

management:  Integración de verificación de reportes. udistrital/planeacion_cliente#705

management:  Integración de verificación de reportes. udistrital/planeacion_cliente#705

---

helpers/seguimientoHelper/seguimiento.helper.go

feat: Ajuste de consulta de indicadores

feat: Ajuste de consulta de indicadores

---

controllers/inversion.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat/se crean funcionalidades de guardado para planes armonizacion y metas #722

feat/se crean funcionalidades de guardado para planes armonizacion y metas #722

---

routers/commentsRouter_controllers.go

fix: Actualización de router

---

helpers/seguimientoHelper/seguimiento.helper.go
models/gestor_documental.go

feat: Cambio de endpoint para formato de archivos. udistrital/planeacion_cliente#728

feat: Cambio de endpoint para formato de archivos. udistrital/planeacion_cliente#728

---

helpers/seguimientoHelper/seguimiento.helper.go
models/gestor_documental.go
routers/commentsRouter_controllers.go

management: Cambio de endpoint para formato de archivos. udistrital/planeacion_cliente#728

management: Cambio de endpoint para formato de archivos. udistrital/planeacion_cliente#728

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: se implementan funcionalidades para armonización y metas de plan de inversión

feat: se implementan funcionalidades para armonización y metas de plan de inversión

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: ajustes para considerar reporte 0/0 . udistrital/planeacion_cliente#727

fix: ajustes para considerar reporte 0/0 . udistrital/planeacion_cliente#727

---

routers/commentsRouter_controllers.go

fix: ajuste de rutas

---

helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go

hotfix: ajuste de rutas

---

controllers/seguimiento.go

fix: ajuste para la primera carga del documento en seguimiento

fix: ajuste para la primera carga del documento en seguimiento

---

controllers/seguimiento.go
routers/commentsRouter_controllers.go

hotfix: ajuste para la primera carga del documento en seguimiento

hotfix: ajuste para la primera carga del documento en seguimiento

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Feat/se implementan funcionalidades para modulo de programación de magnitudes y presupuesto

Feat/se implementan funcionalidades para modulo de programación de magnitudes y presupuesto

---

controllers/inversion.go
controllers/seguimiento.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

managment: se implementan funcionalidades para modulo de programación de magnitudes y presupuesto

managment: se implementan funcionalidades para modulo de programación de magnitudes y presupuesto

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go

fix: se solucionan errores en funcionalidades de programación de metas y tabla resumen modulo planes Inversión

fix: se solucionan errores en funcionalidades de programación de metas y tabla resumen modulo planes Inversión

---

helpers/inversionHelper/inversion.helper.go

fix: se corrige error en inversionhelper para carga de metas plan inversión

fix: se corrige error en inversionhelper para carga de metas plan inversión

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go

hotfix: se corrige error en inversionhelper para carga de metas plan inversión

hotfix: se corrige error en inversionhelper para carga de metas plan inversión

---

controllers/formulacion.go

fix: ajuste en suma de ponderado

fix: ajuste en suma de ponderado

---

controllers/formulacion.go
helpers/inversionHelper/inversion.helper.go

hotfix: ajuste en suma de ponderado

hotfix: ajuste en suma de ponderado

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: ajuste en la carga de resultados de seguimientos planes de acción

fix: ajuste en la carga de resultados de seguimientos planes de acción

---

controllers/formulacion.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: ajuste en la carga de resultados de seguimientos planes de acción

hotfix: ajuste en la carga de resultados de seguimientos planes de acción

---

controllers/inversion.go
helpers/formulacionHelper/formulacion.helper.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: se implementan el ingreso de observaciones estados y roles #742

feat: se implementan el ingreso de observaciones estados y roles #742

---

controllers/inversion.go
helpers/inversionHelper/inversion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: se implementa la funcionalidad de versionamiento #741

feat: se implementa la funcionalidad de versionamiento #741

---

controllers/reportes.go

fix: ajuste de tipo de gráficos en reportes de excelize

fix: ajuste de tipo de gráficos en reportes de excelize

---

controllers/reportes.go
helpers/seguimientoHelper/seguimiento.helper.go

fix: ajuste para consulta de las actividades

hotfix: ajuste para consulta de las actividades

---

controllers/inversion.go
helpers/formulacionHelper/formulacion.helper.go

fix: ajustes corrección de bugs

fix: ajustes corrección de bugs

---

controllers/inversion.go
helpers/formulacionHelper/formulacion.helper.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: ajustes corrección de bugs

hotfix: ajustes corrección de bugs

---

controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

feat: segregación de los detalles de seguimiento por cada actividad evaluada dentro del plan. udistrital/planeacion_cliente#781

feat: segregación de detalles de seguimiento udistrital/planeacion_cliente#781

---

.drone.yml

hotfix: actualización step update_aws_ecs versión goolang

hotfix: actualización step update_aws_ecs versión goolang

---

helpers/evaluacionHelper/evaluacion.helper.go

feat: ajuste en evaluación de planes de acción. udistrital/planeacion_cliente#781

feat: ajuste en evaluación de planes de acción. udistrital/planeacion_cliente#781

---

controllers/seguimiento.go

fix: ajuste en la creación de nuevos seguimientos para un plan avalado

fix: ajuste en la creación de nuevos seguimientos para un plan avalado

---

.drone.yml

hotfix: ajuste en la creación de nuevos seguimientos para un plan avalado

hot fix: ajuste en la creación de nuevos seguimientos para un plan avalado

---

helpers/evaluacionHelper/evaluacion.helper.go

fix: ajuste de reportes con indicadores incompletos

fix: ajuste de reportes con indicadores incompletos

---

helpers/evaluacionHelper/evaluacion.helper.go

Reverts udistrital/planeacion_mid#417

Revert "fix: ajuste de reportes con indicadores incompletos"

---

helpers/evaluacionHelper/evaluacion.helper.go

fix: ajuste de sincronización de ramas

fix: ajuste de sincronización de ramas

---

helpers/seguimientoHelper/seguimiento.helper.go

fix: ajuste de reporte de indicadores segregados para reportes anteriores

fix: ajuste de reporte de indicadores segregados para reportes anteriores

---

helpers/evaluacionHelper/evaluacion.helper.go
helpers/seguimientoHelper/seguimiento.helper.go

hotfix: ajuste de consulta por periodos para el seguimiento

hotfix: ajuste de consulta por periodos para el seguimiento 

---

controllers/formulacion.go
controllers/seguimiento.go

feat: Se crea lógica para heredar seguimientos de actividades a nuevas versiones de planes avalados

feat: Se crea lógica para heredar seguimientos de actividades a nuevas versiones de planes avalados

---

controllers/formulacion.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

management: Se crea lógica para heredar seguimientos de actividades a nuevas versiones de planes avalados

management: Se crea lógica para heredar seguimientos de actividades a nuevas versiones de planes avalados

---

controllers/seguimiento.go

- https://github.com/udistrital/sga_cliente/issues/1343

fix: udistrital/sga_cliente#1343 ajuste migración información

---

controllers/seguimiento.go

feat: ajuste para búsqueda de planes activos

feat: ajuste para búsqueda de planes activos

---

controllers/seguimiento.go

hotfix: ajuste para búsqueda de planes activos

hotfix: ajuste para búsqueda de planes activos

---

controllers/formulacion.go
controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

hotfix: tiene en cuenta nueva estructura en identificacion para docentes y generación de necesidades

hotfix: tiene en cuenta nueva estructura en identificacion para docentes y generación de necesidades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go
static/json/rubros.json

hotfix: add totales rubros identificacion docente, fix producto esperado (tuleap: 56388)

hotfix: add totales rubros identificacion docente, fix producto esperado (tuleap: 56388)

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

managment:  udistrital/sga_cliente#1449 reajuste reporte excel armonización planes vs actividades

managment:  udistrital/sga_cliente#1449 reajuste reporte excel armonización planes vs actividades

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

management: udistrital/sga_cliente#1449 Ajuste version general reportes armonizacion

management: udistrital/sga_cliente#1449 Ajuste version general reportes armonizacion

---

controllers/reportes.go
helpers/evaluacionHelper/evaluacion.helper.go

- https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=57074
- Captura no aval previos trimestres, ajuste calculo indicadores para columna (cumplimiento por actividad)

fix: tuleap(57074) generar reporte noAval previos trimestres, fix val cumpliActividad

---

controllers/reportes.go
helpers/evaluacionHelper/evaluacion.helper.go
helpers/reportesHelper/reportes.helper.go

hotfix: tuleap(57074) generar reporte noAval previos trimestres, fix val cumpliActividad

hotfix: tuleap(57074) generar reporte noAval previos trimestres, fix val cumpliActividad

---

controllers/reportes.go
helpers/reportesHelper/reportes.helper.go

fix: faltaba verificar trimestre vacio en 4to trimestre (tuleap: 57923)

fix: faltaba verificar trimestre vacio en 4to trimestre (tuleap: 57923)

---

controllers/reportes.go

fix: handle number cero en recurso

fix: handle number cero en recurso

---

.env
controllers/formulacion.go
swagger/swagger.json
swagger/swagger.yml

Se agregó validación de rubros en identificación de recurso docente

fix: se agregó validación de rubros en identificación de recurso docente

---

.env
controllers/formulacion.go
controllers/reportes.go
swagger/swagger.json
swagger/swagger.yml

fix: corrección de Bugs en SISGPLAN

fix: corrección de Bugs en SISGPLAN

---

controllers/seguimiento.go
routers/commentsRouter_controllers.go

Se implementaron rutas para verificar la revisión de un plan tanto en seguimiento como en formulación.

feat: implementacion de rutas para la verificar revisiones en seguimiento y formulación

---

swagger/swagger.json
swagger/swagger.yml

fix: generación del Swagger

---

conf/app.conf
controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

[#843](https://github.com/udistrital/planeacion_cliente/issues/843)
Se realizaron ajustes al controlador

feat: Controlador para calculos identificación docentes

---

helpers/formulacionHelper/formulacion.helper.go

[#842](https://github.com/udistrital/planeacion_cliente/issues/842)
Actualizaciones en controlador calculos identificación docentes

feat: Desarrollo controlador calculos identificación docentes

---

helpers/formulacionHelper/formulacion.helper.go

[#884](https://github.com/udistrital/planeacion_cliente/issues/884)
Ajustes controlador calculos identificación docente

feat: Ajustes controlador calculos identificación docente

---

main.go

fix: adición de XRAY

---

controllers/seguimiento.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Se implementó un controlador que obtiene todos los datos necesarios para consultar el seguimiento de un plan por trimestres.

feat: controlador que obtiene todos los planes en seguimiento

---

controllers/formulacion.go
controllers/planes_accion.go
helpers/formulacionHelper/formulacion.helper.go
helpers/planesAccionHelper/planes_accion.helper.go
helpers/utilidades.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

Creación de rutas para la nueva funcionalidad con issues: udistrital/planeacion_cliente/issues/849 y udistrital/planeacion_cliente/issues/866

feat: resumen de planes de acción

---

helpers/formulacionHelper/formulacion.helper.go

feat: se agregaron nuevos campos en la obtención de planes

feat: se agregaron nuevos campos en la obtención de planes

---

controllers/seguimiento.go
swagger/swagger.json
swagger/swagger.yml

fix: corrección del swagger plan_id

fix: corrección del swagger plan_id

---

.drone.yml
controllers/formulacion.go
helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

[#888](https://github.com/udistrital/planeacion_cliente/issues/888)
Actualización estructura planes según plantilla

feat: Actualización estructura planes según plantilla

---

.drone.yml
helpers/planesAccionHelper/planes_accion.helper.go

Corrección en nombre de variable

feat: Corrección en nombre de variable en resumen de planes de acción

---

helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go

[#877](https://github.com/udistrital/planeacion_cliente/issues/877)
- Ajuste lógica de componentes en el cliente asociados a la modificación de plantillas de planes de acción en formulación

fix: Actualización estructura planes, corrección al inactivar un nivel

---

helpers/formatoHelper/formato.helper.go
helpers/formulacionHelper/formulacion.helper.go
helpers/planesAccionHelper/planes_accion.helper.go

feat: cambios realizados en sprint 4 y 5

feat: cambios realizados en sprint 4 y 5

---

controllers/evaluacion.go
helpers/evaluacionHelper/evaluacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Creación de ruta para suplir las necesidades de la issue: https://github.com/udistrital/planeacion_cliente/issues/916

feat: Ruta para recibir los nombres de los planes en evaluación

---

.drone.yml
controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Se agregaron servicios para realizar el almacenamiento de planes y unidades de interés en periodo-seguimiento

feat: se agregaron servicios para realizar el almacenamiento de planes y unidades de interés en periodo-seguimiento

---

controllers/formulacion.go
controllers/seguimiento.go
helpers/formulacionHelper/formulacion.helper.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

- Se agregó la creación de registros de seguimiento para planes con nueva estructura.
- Se modificó la petición para obtener la dependencia porque estaba fallando.

feat: se agregó la creación de registros de seguimiento para planes con nueva estructura

---

controllers/evaluacion.go
helpers/evaluacionHelper/evaluacion.helper.go
helpers/formulacionHelper/formulacion.helper.go
helpers/utilidades.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Migración de la lógica para obtener el promedio de avance en los planes que están disponibles para evaluación udistrital/planeacion_cliente/issues/926

feat: Se migra la lógica del avance promedio

---

helpers/formulacionHelper/formulacion.helper.go

[#987](https://github.com/udistrital/planeacion_cliente/issues/987)
Corrección de peticiones en la edición de plantillas

fix: Corrección de peticiones en la edición de plantillas

---

helpers/seguimientoHelper/seguimiento.helper.go

- Se quitaron las goroutines de ObtenerTrimestres en el helper de seguimiento

Fix: obtener trimestres seguimiento

---

helpers/evaluacionHelper/evaluacion.helper.go

https://github.com/udistrital/planeacion_cliente/issues/1049

Feat: Limitacion funcion GetPeriodos para que el funcionamiento de el guardado de data sea correcto.

---

controllers/evaluacion.go
helpers/evaluacionHelper/evaluacion.helper.go

https://github.com/udistrital/planeacion_cliente/issues/1049

feat: Re-ajuste limite de periodos 

---

controllers/reportes.go

https://github.com/udistrital/planeacion_cliente/issues/1049

fix: correccion archivo c.reportes 

---

controllers/formulacion.go

- Se elimina la validacion relacionada al tema de la ponderación.

fix: CORRECCION_DE_PONDERACION

---

controllers/evaluacion.go
controllers/reportes.go
helpers/evaluacionHelper/evaluacion.helper.go

- https://github.com/udistrital/planeacion_cliente/issues/1151

fix: cargar de indicadores en evaluación

---

controllers/reportes.go
helpers/evaluacionHelper/evaluacion.helper.go

- https://github.com/udistrital/planeacion_cliente/issues/1151

fix: Traida de evaluacion

---

controllers/formulacion.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

https://github.com/udistrital/planeacion_cliente/issues/1063

fix: id_actividad seguimiento

---

controllers/reportes.go

- Se agregó validación de generación de reportes con una única actividad

feat: se agregó validación de generación de reportes con una única actividad

---

main.go

para no acceder de otra origen que *udistrital.edu.co / https://github.com/udistrital/planeacion_cliente/issues/1239

feat:configuracion de cors 

---

helpers/formulacionHelper/formulacion.helper.go
main.go

*udistrital.edu.co / udistrital/planeacion_cliente#1239

feat:configuracion de cors

---

main.go

/ https://github.com/udistrital/planeacion_cliente/issues/1239

feat:update main agregando el consumo de auditoria 

---

controllers/formulacion.go
helpers/formulacionHelper/formulacion.helper.go
helpers/inversionHelper/inversion.helper.go

- Se realiza el cambio para que se permita guardar las observaciones con campos vacíos, en fase de formulación.

fix: correccion_observaciones_sin_texto

---

controllers/reportes.go
controllers/seguimiento.go
helpers/seguimientoHelper/seguimiento.helper.go

- https://github.com/udistrital/planeacion_cliente/issues/1221
- https://github.com/udistrital/planeacion_cliente/issues/1238

feat: ajustes reportes

---

controllers/reportes.go

Pequeña corrección
- https://github.com/udistrital/planeacion_cliente/issues/1221

feat: correccion de titulos de trimestres en reporte de evaluación
